### ISSUE TITLE
Rack::Utils.bytesize is deprecated in Rack 2.0 and will be removed in Rack 3. Use String#bytesize instead.

### ISSUE THREAD

**Issue by devowhippit** [trenton42/middleman-inline-style#2]
Having a little trouble pushing a fix branch I made in `lib/rack-middleware.rb` line 34 to fix this issue;

```headers['Content-Length'] = Rack::Utils.bytesize(newbody).to_s```

to 

```headers['Content-Length'] = newbody.bytesize.to_s```

More of a Github problem than an issue with the repo.

**Comment by trenton42** [comment]
Fixed in #3
